In [21]:
from tensorflow.keras.preprocessing.text import one_hot

In [22]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [23]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [24]:
## Define the vocabulary size
voc_size=10000

In [25]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7301, 5423, 1723, 8784],
 [7301, 5423, 1723, 8379],
 [7301, 3680, 1723, 26],
 [589, 3453, 7062, 9889, 3611],
 [589, 3453, 7062, 9889, 8434],
 [8103, 7301, 179, 1723, 9961],
 [3074, 6227, 507, 9889]]

In [26]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [27]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [28]:
import numpy as np

In [29]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7301 5423 1723 8784]
 [   0    0    0    0 7301 5423 1723 8379]
 [   0    0    0    0 7301 3680 1723   26]
 [   0    0    0  589 3453 7062 9889 3611]
 [   0    0    0  589 3453 7062 9889 8434]
 [   0    0    0 8103 7301  179 1723 9961]
 [   0    0    0    0 3074 6227  507 9889]]


In [30]:
## feature representation
dim=10

In [31]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [32]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [33]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 17ms/step


array([[[-0.01996322, -0.04784488,  0.03783106,  0.02626697,
         -0.04495324,  0.02472461,  0.01424283, -0.02874239,
         -0.03772533, -0.04331973],
        [-0.01996322, -0.04784488,  0.03783106,  0.02626697,
         -0.04495324,  0.02472461,  0.01424283, -0.02874239,
         -0.03772533, -0.04331973],
        [-0.01996322, -0.04784488,  0.03783106,  0.02626697,
         -0.04495324,  0.02472461,  0.01424283, -0.02874239,
         -0.03772533, -0.04331973],
        [-0.01996322, -0.04784488,  0.03783106,  0.02626697,
         -0.04495324,  0.02472461,  0.01424283, -0.02874239,
         -0.03772533, -0.04331973],
        [ 0.0389192 ,  0.02015287, -0.02210097, -0.01085787,
         -0.01290826, -0.04532801,  0.02740692,  0.03551463,
          0.03837437, -0.03879293],
        [-0.0446431 , -0.03937008,  0.02363053, -0.00425197,
         -0.03728129, -0.00070995, -0.04877762,  0.03903026,
         -0.0281544 ,  0.02492431],
        [-0.04584515,  0.01608719, -0.00833571,  0.0

In [34]:
embedded_docs[0]

array([   0,    0,    0,    0, 7301, 5423, 1723, 8784], dtype=int32)

In [35]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 16ms/step


array([[-0.01996322, -0.04784488,  0.03783106,  0.02626697, -0.04495324,
         0.02472461,  0.01424283, -0.02874239, -0.03772533, -0.04331973],
       [-0.01996322, -0.04784488,  0.03783106,  0.02626697, -0.04495324,
         0.02472461,  0.01424283, -0.02874239, -0.03772533, -0.04331973],
       [-0.01996322, -0.04784488,  0.03783106,  0.02626697, -0.04495324,
         0.02472461,  0.01424283, -0.02874239, -0.03772533, -0.04331973],
       [-0.01996322, -0.04784488,  0.03783106,  0.02626697, -0.04495324,
         0.02472461,  0.01424283, -0.02874239, -0.03772533, -0.04331973],
       [ 0.0389192 ,  0.02015287, -0.02210097, -0.01085787, -0.01290826,
        -0.04532801,  0.02740692,  0.03551463,  0.03837437, -0.03879293],
       [-0.0446431 , -0.03937008,  0.02363053, -0.00425197, -0.03728129,
        -0.00070995, -0.04877762,  0.03903026, -0.0281544 ,  0.02492431],
       [-0.04584515,  0.01608719, -0.00833571,  0.03124653,  0.01368923,
        -0.02142587, -0.0266923 ,  0.01584354